FROM python:3 AS build

COPY requirements.txt .

RUN python -m pip install --user --no-cache-dir -r requirements.txt

FROM python:3-alpine

COPY --from=build /root/.local /root/.local
WORKDIR /usr/src/app

COPY app_db.py .
COPY model.py .

ENV PATH = /root/.local:$PATH
ENV RABBIT_HOST = localhost
ENV DB_HOST = localhost
ENV DB_USER = root
ENV DB_PWD = 1234567
ENV DB_NAME = call_center

CMD [ "python", "-u", "./app_db.py"]